development:
  AWS_ACCESS_KEY_ID: 'AKIAIAV4CMOAX6IJWBAQ'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'expense1'
test:
  AWS_ACCESS_KEY_ID: 'AKIAIAV4CMOAX6IJWBAQ'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'expense1'
production:
  AWS_ACCESS_KEY_ID: 'AKIAIAV4CMOAX6IJWBAQ'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'expense1'